PREFIX ub:<http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dbo:<http://dbpedia.org/ontology/>
PREFIX dbr:<http://dbpedia.org/resource/>
PREFIX dbp:<http://dbpedia.org/property/>
PREFIX yago:<http://dbpedia.org/class/yago/>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
PREFIX :<http://example.org/>
SELECT DISTINCT ?x WHERE {
        ?x a dbo:Film. 
        ?x dbo:starring ?varnameistegal.
        ?x dbo:imdbId ?p_2.
        ?x dbp:studio dbr:Walt_Disney_Pictures
}
